<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRba9xSx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRba9xSx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRba9xSx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRba9xSx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRba9xSx\App_KernelDevDebugContainer([
    'container.build_hash' => 'Rba9xSx',
    'container.build_id' => '980216cf',
    'container.build_time' => 1674469149,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRba9xSx');
